name: Generate readme.md
on:
  push:
    branches:
      - main
    paths:
      - src/yaml/*.yml
      - src/md/*.md
      - src/readme.ts

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate
        run: pnpm generate

      - name: Commit
        run: |
          git add README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "chore: generate README.md"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
